# Generated by Django 4.0.2 on 2022-08-03 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_quize', models.TextField()),
                ('major', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('right_answer', models.IntegerField()),
                ('quize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='quize.relation')),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_question', to='quize.questions')),
            ],
        ),
    ]
